### ISSUE TITLE
'Settings' and 'About Me' pages could be consolidated

### ISSUE THREAD

**Issue by WhaleJ84** [solentcomputingsociety/solentcomputingsociety.github.io#1]
The content in both the Settings and About Me pages contain options that are both relevant to the same things.
It could be an idea to move the options from one page into another to make things clearer for the user.

**Comment by solent-computing-society** [comment]
Addressed in commit [0d668be2e224375d37a7f6603cc544e70f88afff](https://github.com/solentcomputingsociety/solentcomputingsociety.github.io/commit/0d668be2e224375d37a7f6603cc544e70f88afff)
