### ISSUE TITLE
'Website URL' section in 'About Me' page regex too restrictive

### ISSUE THREAD

**Issue by WhaleJ84** [solentcomputingsociety/solentcomputingsociety.github.io#2]
When trying to add in my website to the entry box, it wouldn't allow it without the addition of 'www.' in front of it.
With the way of website URLs going, this seems like a restriction that will become more cumbersome in future.

**Comment by solent-computing-society** [comment]
Addressed in commit [7f09090dc0fd5aedbc1cc3b5e2b3bd8fb0105026](https://github.com/solentcomputingsociety/solentcomputingsociety.github.io/commit/7f09090dc0fd5aedbc1cc3b5e2b3bd8fb0105026).
