### ISSUE TITLE
Website will never load if certain JS scripts are blocked

### ISSUE THREAD

**Issue by WhaleJ84** [solentcomputingsociety/solentcomputingsociety.github.io#3]
Steps to reproduce:
Browser - Firefox
Addon - Privacy Badger
URL - https://solentcomputingsociety.github.io/app/

Observing the network interactions, when the `script.google.com` domain is blocked by a privacy extension, the page will simply eternally show a loading page.
I propose a way to inform the user that their extension is preventing their access to give a bit of feedback.

**Comment by bradley499** [comment]
Addressed in commit https://github.com/solentcomputingsociety/solentcomputingsociety.github.io/commit/d82a994444f68e7695b9fb83849afde466e09cca
